/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZaNasRouteImport } from './routes/za-nas'
import { Route as UslugiRouteImport } from './routes/uslugi'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SeoOptimizatsiyaVarnaRouteImport } from './routes/seo-optimizatsiya-varna'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProektiRouteImport } from './routes/proekti'
import { Route as PolitikaZaPoveritelnostGdprRouteImport } from './routes/politika-za-poveritelnost-gdpr'
import { Route as PolitikaZaBiskvitkiRouteImport } from './routes/politika-za-biskvitki'
import { Route as ObshtiUsloviaRouteImport } from './routes/obshti-uslovia'
import { Route as MarketingAgentsiyaVarnaRouteImport } from './routes/marketing-agentsiya-varna'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as KontaktiRouteImport } from './routes/kontakti'
import { Route as IzrabotkaNaSaytVarnaRouteImport } from './routes/izrabotka-na-sayt-varna'
import { Route as IzrabotkaNaOnlaynMagazinVarnaRouteImport } from './routes/izrabotka-na-onlayn-magazin-varna'
import { Route as AppRouteImport } from './routes/app'
import { Route as AiAgentsiyaVarnaRouteImport } from './routes/ai-agentsiya-varna'
import { Route as IndexRouteImport } from './routes/index'

const ZaNasRoute = ZaNasRouteImport.update({
  id: '/za-nas',
  path: '/za-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiRoute = UslugiRouteImport.update({
  id: '/uslugi',
  path: '/uslugi',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoOptimizatsiyaVarnaRoute = SeoOptimizatsiyaVarnaRouteImport.update({
  id: '/seo-optimizatsiya-varna',
  path: '/seo-optimizatsiya-varna',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProektiRoute = ProektiRouteImport.update({
  id: '/proekti',
  path: '/proekti',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitikaZaPoveritelnostGdprRoute =
  PolitikaZaPoveritelnostGdprRouteImport.update({
    id: '/politika-za-poveritelnost-gdpr',
    path: '/politika-za-poveritelnost-gdpr',
    getParentRoute: () => rootRouteImport,
  } as any)
const PolitikaZaBiskvitkiRoute = PolitikaZaBiskvitkiRouteImport.update({
  id: '/politika-za-biskvitki',
  path: '/politika-za-biskvitki',
  getParentRoute: () => rootRouteImport,
} as any)
const ObshtiUsloviaRoute = ObshtiUsloviaRouteImport.update({
  id: '/obshti-uslovia',
  path: '/obshti-uslovia',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingAgentsiyaVarnaRoute = MarketingAgentsiyaVarnaRouteImport.update({
  id: '/marketing-agentsiya-varna',
  path: '/marketing-agentsiya-varna',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktiRoute = KontaktiRouteImport.update({
  id: '/kontakti',
  path: '/kontakti',
  getParentRoute: () => rootRouteImport,
} as any)
const IzrabotkaNaSaytVarnaRoute = IzrabotkaNaSaytVarnaRouteImport.update({
  id: '/izrabotka-na-sayt-varna',
  path: '/izrabotka-na-sayt-varna',
  getParentRoute: () => rootRouteImport,
} as any)
const IzrabotkaNaOnlaynMagazinVarnaRoute =
  IzrabotkaNaOnlaynMagazinVarnaRouteImport.update({
    id: '/izrabotka-na-onlayn-magazin-varna',
    path: '/izrabotka-na-onlayn-magazin-varna',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentsiyaVarnaRoute = AiAgentsiyaVarnaRouteImport.update({
  id: '/ai-agentsiya-varna',
  path: '/ai-agentsiya-varna',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-agentsiya-varna': typeof AiAgentsiyaVarnaRoute
  '/app': typeof AppRoute
  '/izrabotka-na-onlayn-magazin-varna': typeof IzrabotkaNaOnlaynMagazinVarnaRoute
  '/izrabotka-na-sayt-varna': typeof IzrabotkaNaSaytVarnaRoute
  '/kontakti': typeof KontaktiRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/marketing-agentsiya-varna': typeof MarketingAgentsiyaVarnaRoute
  '/obshti-uslovia': typeof ObshtiUsloviaRoute
  '/politika-za-biskvitki': typeof PolitikaZaBiskvitkiRoute
  '/politika-za-poveritelnost-gdpr': typeof PolitikaZaPoveritelnostGdprRoute
  '/proekti': typeof ProektiRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/seo-optimizatsiya-varna': typeof SeoOptimizatsiyaVarnaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uslugi': typeof UslugiRoute
  '/za-nas': typeof ZaNasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-agentsiya-varna': typeof AiAgentsiyaVarnaRoute
  '/app': typeof AppRoute
  '/izrabotka-na-onlayn-magazin-varna': typeof IzrabotkaNaOnlaynMagazinVarnaRoute
  '/izrabotka-na-sayt-varna': typeof IzrabotkaNaSaytVarnaRoute
  '/kontakti': typeof KontaktiRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/marketing-agentsiya-varna': typeof MarketingAgentsiyaVarnaRoute
  '/obshti-uslovia': typeof ObshtiUsloviaRoute
  '/politika-za-biskvitki': typeof PolitikaZaBiskvitkiRoute
  '/politika-za-poveritelnost-gdpr': typeof PolitikaZaPoveritelnostGdprRoute
  '/proekti': typeof ProektiRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/seo-optimizatsiya-varna': typeof SeoOptimizatsiyaVarnaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uslugi': typeof UslugiRoute
  '/za-nas': typeof ZaNasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-agentsiya-varna': typeof AiAgentsiyaVarnaRoute
  '/app': typeof AppRoute
  '/izrabotka-na-onlayn-magazin-varna': typeof IzrabotkaNaOnlaynMagazinVarnaRoute
  '/izrabotka-na-sayt-varna': typeof IzrabotkaNaSaytVarnaRoute
  '/kontakti': typeof KontaktiRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/marketing-agentsiya-varna': typeof MarketingAgentsiyaVarnaRoute
  '/obshti-uslovia': typeof ObshtiUsloviaRoute
  '/politika-za-biskvitki': typeof PolitikaZaBiskvitkiRoute
  '/politika-za-poveritelnost-gdpr': typeof PolitikaZaPoveritelnostGdprRoute
  '/proekti': typeof ProektiRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/seo-optimizatsiya-varna': typeof SeoOptimizatsiyaVarnaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uslugi': typeof UslugiRoute
  '/za-nas': typeof ZaNasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-agentsiya-varna'
    | '/app'
    | '/izrabotka-na-onlayn-magazin-varna'
    | '/izrabotka-na-sayt-varna'
    | '/kontakti'
    | '/llms.txt'
    | '/marketing-agentsiya-varna'
    | '/obshti-uslovia'
    | '/politika-za-biskvitki'
    | '/politika-za-poveritelnost-gdpr'
    | '/proekti'
    | '/robots.txt'
    | '/seo-optimizatsiya-varna'
    | '/sitemap.xml'
    | '/uslugi'
    | '/za-nas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-agentsiya-varna'
    | '/app'
    | '/izrabotka-na-onlayn-magazin-varna'
    | '/izrabotka-na-sayt-varna'
    | '/kontakti'
    | '/llms.txt'
    | '/marketing-agentsiya-varna'
    | '/obshti-uslovia'
    | '/politika-za-biskvitki'
    | '/politika-za-poveritelnost-gdpr'
    | '/proekti'
    | '/robots.txt'
    | '/seo-optimizatsiya-varna'
    | '/sitemap.xml'
    | '/uslugi'
    | '/za-nas'
  id:
    | '__root__'
    | '/'
    | '/ai-agentsiya-varna'
    | '/app'
    | '/izrabotka-na-onlayn-magazin-varna'
    | '/izrabotka-na-sayt-varna'
    | '/kontakti'
    | '/llms.txt'
    | '/marketing-agentsiya-varna'
    | '/obshti-uslovia'
    | '/politika-za-biskvitki'
    | '/politika-za-poveritelnost-gdpr'
    | '/proekti'
    | '/robots.txt'
    | '/seo-optimizatsiya-varna'
    | '/sitemap.xml'
    | '/uslugi'
    | '/za-nas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAgentsiyaVarnaRoute: typeof AiAgentsiyaVarnaRoute
  AppRoute: typeof AppRoute
  IzrabotkaNaOnlaynMagazinVarnaRoute: typeof IzrabotkaNaOnlaynMagazinVarnaRoute
  IzrabotkaNaSaytVarnaRoute: typeof IzrabotkaNaSaytVarnaRoute
  KontaktiRoute: typeof KontaktiRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  MarketingAgentsiyaVarnaRoute: typeof MarketingAgentsiyaVarnaRoute
  ObshtiUsloviaRoute: typeof ObshtiUsloviaRoute
  PolitikaZaBiskvitkiRoute: typeof PolitikaZaBiskvitkiRoute
  PolitikaZaPoveritelnostGdprRoute: typeof PolitikaZaPoveritelnostGdprRoute
  ProektiRoute: typeof ProektiRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SeoOptimizatsiyaVarnaRoute: typeof SeoOptimizatsiyaVarnaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UslugiRoute: typeof UslugiRoute
  ZaNasRoute: typeof ZaNasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/za-nas': {
      id: '/za-nas'
      path: '/za-nas'
      fullPath: '/za-nas'
      preLoaderRoute: typeof ZaNasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi': {
      id: '/uslugi'
      path: '/uslugi'
      fullPath: '/uslugi'
      preLoaderRoute: typeof UslugiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-optimizatsiya-varna': {
      id: '/seo-optimizatsiya-varna'
      path: '/seo-optimizatsiya-varna'
      fullPath: '/seo-optimizatsiya-varna'
      preLoaderRoute: typeof SeoOptimizatsiyaVarnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proekti': {
      id: '/proekti'
      path: '/proekti'
      fullPath: '/proekti'
      preLoaderRoute: typeof ProektiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politika-za-poveritelnost-gdpr': {
      id: '/politika-za-poveritelnost-gdpr'
      path: '/politika-za-poveritelnost-gdpr'
      fullPath: '/politika-za-poveritelnost-gdpr'
      preLoaderRoute: typeof PolitikaZaPoveritelnostGdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politika-za-biskvitki': {
      id: '/politika-za-biskvitki'
      path: '/politika-za-biskvitki'
      fullPath: '/politika-za-biskvitki'
      preLoaderRoute: typeof PolitikaZaBiskvitkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obshti-uslovia': {
      id: '/obshti-uslovia'
      path: '/obshti-uslovia'
      fullPath: '/obshti-uslovia'
      preLoaderRoute: typeof ObshtiUsloviaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing-agentsiya-varna': {
      id: '/marketing-agentsiya-varna'
      path: '/marketing-agentsiya-varna'
      fullPath: '/marketing-agentsiya-varna'
      preLoaderRoute: typeof MarketingAgentsiyaVarnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakti': {
      id: '/kontakti'
      path: '/kontakti'
      fullPath: '/kontakti'
      preLoaderRoute: typeof KontaktiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/izrabotka-na-sayt-varna': {
      id: '/izrabotka-na-sayt-varna'
      path: '/izrabotka-na-sayt-varna'
      fullPath: '/izrabotka-na-sayt-varna'
      preLoaderRoute: typeof IzrabotkaNaSaytVarnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/izrabotka-na-onlayn-magazin-varna': {
      id: '/izrabotka-na-onlayn-magazin-varna'
      path: '/izrabotka-na-onlayn-magazin-varna'
      fullPath: '/izrabotka-na-onlayn-magazin-varna'
      preLoaderRoute: typeof IzrabotkaNaOnlaynMagazinVarnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agentsiya-varna': {
      id: '/ai-agentsiya-varna'
      path: '/ai-agentsiya-varna'
      fullPath: '/ai-agentsiya-varna'
      preLoaderRoute: typeof AiAgentsiyaVarnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAgentsiyaVarnaRoute: AiAgentsiyaVarnaRoute,
  AppRoute: AppRoute,
  IzrabotkaNaOnlaynMagazinVarnaRoute: IzrabotkaNaOnlaynMagazinVarnaRoute,
  IzrabotkaNaSaytVarnaRoute: IzrabotkaNaSaytVarnaRoute,
  KontaktiRoute: KontaktiRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  MarketingAgentsiyaVarnaRoute: MarketingAgentsiyaVarnaRoute,
  ObshtiUsloviaRoute: ObshtiUsloviaRoute,
  PolitikaZaBiskvitkiRoute: PolitikaZaBiskvitkiRoute,
  PolitikaZaPoveritelnostGdprRoute: PolitikaZaPoveritelnostGdprRoute,
  ProektiRoute: ProektiRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SeoOptimizatsiyaVarnaRoute: SeoOptimizatsiyaVarnaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UslugiRoute: UslugiRoute,
  ZaNasRoute: ZaNasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
